version: "3.8"

services:
  db:
    image: postgres:15
    container_name: govtech_postgres
    restart: always
    environment:
      POSTGRES_USER: govtech_user
      POSTGRES_PASSWORD: govtech_password
      POSTGRES_DB: govtech_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: govtech_neo4j
    environment:
      NEO4J_AUTH: neo4j/govtech_password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
